# Generated by Django 5.0.4 on 2024-04-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_column='category_name', default=1, on_delete=django.db.models.deletion.CASCADE, to='dash.category'),
        ),
    ]
