# Generated by Django 5.0.4 on 2024-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_rename_category_products_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
