# Generated by Django 5.0.4 on 2024-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
